<?php
$widget = [
  "Eloom_ProductFilter/js/firstload" => [
    "ajaxUrl" => $this->getUrl('productfilter/index/firstLoad'),
    "currentUrl" => $this->getUrl(),
    "jsonData" => $this->getFilterData()
  ]
]
?>
<div class="no-loaded" data-mage-init='<?= json_encode($widget) ?>'>
    <div class="brand-loader double-bounce-spinner">
        <div class="double-bounce1"></div>
        <div class="double-bounce2"></div>
    </div>
</div>
