var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,b,c){a instanceof String&&(a=String(a));for(var e=a.length,d=0;d<e;d++){var f=a[d];if(b.call(c,f,d,a))return{i:d,v:f}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,b){var c=$jscomp.propertyToPolyfillSymbol[b];if(null==c)return a[b];c=a[c];return void 0!==c?c:a[b]};
$jscomp.polyfill=function(a,b,c,e){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,c,e):$jscomp.polyfillUnisolated(a,b,c,e))};$jscomp.polyfillUnisolated=function(a,b,c,e){c=$jscomp.global;a=a.split(".");for(e=0;e<a.length-1;e++){var d=a[e];if(!(d in c))return;c=c[d]}a=a[a.length-1];e=c[a];b=b(e);b!=e&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,c,e){var d=a.split(".");a=1===d.length;e=d[0];e=!a&&e in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var f=0;f<d.length-1;f++){var g=d[f];if(!(g in e))return;e=e[g]}d=d[d.length-1];c=$jscomp.IS_SYMBOL_NATIVE&&"es6"===c?e[d]:null;b=b(c);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,d,{configurable:!0,writable:!0,value:b}):b!==c&&($jscomp.propertyToPolyfillSymbol[d]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(d):$jscomp.POLYFILL_PREFIX+d,d=
$jscomp.propertyToPolyfillSymbol[d],$jscomp.defineProperty(e,d,{configurable:!0,writable:!0,value:b})))};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(b,c){return $jscomp.findInternal(this,b,c).v}},"es6","es3");
(function(a){"function"===typeof define&&define.amd?define(["jquery","jquery-ui-modules/widget","catalogAddToCart"],a):a(jQuery)})(function(a){a.widget("eloom.ajaxInfiniteLoad",{options:{trigger:"[data-role=ajax_trigger]",itemsWrap:".product-items",ajaxLoader:"[data-role=ajax_loader]",currentUrl:"",formKeyInputSelector:'input[name="form_key"]'},_currentPage:1,_create:function(){var b=this;b.element.find(b.options.trigger).click(function(){b._ajaxLoadProducts()})},_ajaxLoadProducts:function(){var b=
this,c=this.options,e=b.element.find(c.trigger),d=b.element.find(c.ajaxLoader),f=!1;b.element.find(".product-item");e.hide();d.show();b._currentPage++;c.jsonData.cur_page=b._currentPage;c.jsonData.current_url=c.currentUrl;jQuery.ajax({url:c.ajaxUrl,type:"GET",data:c.jsonData,cache:!0,success:function(g){"undefined"!==typeof g.now&&(window.eloom.now=g.now);g.html&&(b.formKey=a(c.formKeyInputSelector).first().val(),a(c.itemsWrap,b.element).append(g.html),setTimeout(function(){b.element.find('[name="form_key"]').each(function(){a(this).val(b.formKey)})},
500),"undefined"!==typeof window.angularCompileElement&&window.angularCompileElement(b.element));g.last_page<=b._currentPage&&(f=!0);require(["mage/apply/main"],function(h){h&&h.apply();a("body").trigger("contentUpdated");setTimeout(function(){a("body").trigger("ajaxProductInfiniteLoaded")},100)})},error:function(g,h,k){b._currentPage--;console.error(h)}}).always(function(){d.hide();f?e.hide():e.show()})}});return a.eloom.ajaxInfiniteLoad});
